sudo: false

notifications:
  slack: hkuplgroup:7jiTM7QOayfuaA2tm7YgOhHa

branches:
  only:
    - master
    - develop

language: java

jdk:
  - oraclejdk8

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-7.10.2
    - libgmp-dev
    - alex-3.1.4
    - happy-1.19.5

before_install:
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.4.0/stack-0.1.4.0-x86_64-linux.tar.gz | tar xzf - && mv -f stack ~/.local/bin
  - export PATH=/opt/ghc/7.10.2/bin:$PATH
  - export PATH=/opt/happy/1.19.5/bin:/opt/alex/3.1.4/bin:$PATH

install:
  - stack --no-terminal setup
  - make runtime
  - stack --no-terminal install
  - make prerequisite
  - make mkprelude
  - make runtime
  - stack --no-terminal install

script:
  - stack --no-terminal test

cache:
  directories:
  - $HOME/.stack
