sudo: false

notifications:
  slack: hkuplgroup:7jiTM7QOayfuaA2tm7YgOhHa

branches:
  only:
    - master
    - develop
    - testsuite
    - ghc-7.10

language: java

env:
  #- GHCVER=7.4.2
  #- GHCVER=7.6.3
  #- GHCVER=7.8.3
  - GHCVER=7.10.1
  #- GHCVER=head
  # - >
  #   GHCVER=7.4.2
  #   MODE="-fsafe"

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-7.10.1

jdk:
  - oraclejdk8

before_install:
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.2.0/stack-0.1.2.0-x86_64-linux.gz | gunzip > ~/.local/bin/stack
  - chmod a+x ~/.local/bin/stack
  # let stack download ghc
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH


install:
  - stack setup --no-terminal

script:
  - make test

cache:
  directories:
  - $HOME/.stack
